# How many distinct terms are in the sequence generated by ab for 2 lte a lte 100 and 2 lte b lte 100?

n = 500
ns = []

2.upto(n) do |a|
	# 1st approach:
	#2.upto(n) do |b|
	#	ns << a**b
	#end
	# 2nd approach: (3x faster)
	b = a
	(n-1).times do
		ns << (b*=a)
	end
end

puts ns.uniq.size